stages:
  - test

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: docker:20.10.16-dind
    alias: docker

test:integration:
  stage: test
  image: cimg/node:18.17
  before_script:
    - apk add --no-cache curl docker-cli docker-compose
  script:
    - docker-compose up -d --build
    - npx cypress run --config baseUrl=http://localhost:3000
  only:
    - main